"""FraudAlert model — Phase 5 Fraud Detection Engine."""

from datetime import datetime, timezone
from enum import Enum
from uuid import UUID, uuid4

from sqlalchemy import Column, DateTime, String, ForeignKey, Float, Text, Index, JSON
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class Severity(str, Enum):
    """Alert severity enum."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, Enum):
    """Alert status enum."""
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    CLOSED = "CLOSED"
    FALSE_POSITIVE = "FALSE_POSITIVE"


class FraudAlert(Base):
    """Fraud alert generated by Fraud Detection Engine."""

    __tablename__ = "fraud_alerts"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, default=uuid4
    )

    # Human-readable alert ID like ALT20260816123456
    alert_id: Mapped[str] = mapped_column(
        String(30), unique=True, nullable=False, index=True
    )

    # Foreign keys
    transaction_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("transactions.id", ondelete="CASCADE"),
        nullable=False, index=True
    )
    account_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("accounts.id", ondelete="CASCADE"),
        nullable=False, index=True
    )

    # Alert properties
    alert_type: Mapped[str] = mapped_column(
        String(100), nullable=False
    )
    risk_score: Mapped[float] = mapped_column(
        Float, nullable=False, index=True
    )
    severity: Mapped[str] = mapped_column(
        String(20), default=Severity.LOW.value, nullable=False, index=True
    )
    description: Mapped[str] = mapped_column(
        Text, nullable=False
    )
    rule_breakdown: Mapped[dict | None] = mapped_column(
        JSON, nullable=True
    )
    status: Mapped[str] = mapped_column(
        String(20), default=AlertStatus.OPEN.value, nullable=False, index=True
    )

    # Timestamp
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False, index=True
    )

    # Relationships
    transaction: Mapped["Transaction"] = relationship(
        "Transaction", foreign_keys=[transaction_id], backref="fraud_alerts"
    )
    account: Mapped["Account"] = relationship(
        "Account", foreign_keys=[account_id], backref="fraud_alerts"
    )

    def __repr__(self) -> str:
        return f"<FraudAlert(alert_id={self.alert_id!r}, severity={self.severity!r}, risk_score={self.risk_score})>"


Index("ix_fraud_alerts_severity_status", "severity", "status")
