"""Create accounts and transactions tables.

Revision ID: 2024_create_accounts_transactions
Revises: 2024_add_auth_fields_to_users
Create Date: 2024-01-15 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2024_create_accounts_transactions"
down_revision: Union[str, None] = "2024_add_auth_fields_to_users"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("account_number", sa.String(20), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("balance", sa.DECIMAL(precision=18, scale=2), nullable=False,
                  server_default=sa.text("'100000.00'")),
        sa.Column("status", sa.String(20), nullable=False,
                  server_default=sa.text("'active'")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_number"),
    )
    op.create_index("ix_accounts_account_number", "accounts", ["account_number"], unique=True)
    op.create_index("ix_accounts_user_id", "accounts", ["user_id"], unique=False)

    op.create_table(
        "transactions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("transaction_id", sa.String(30), nullable=False),
        sa.Column("sender_account_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("receiver_account_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=18, scale=2), nullable=False),
        sa.Column("remark", sa.String(500), nullable=True),
        sa.Column("status", sa.String(20), nullable=False,
                  server_default=sa.text("'completed'")),
        sa.Column("device_info", sa.String(500), nullable=True),
        sa.Column("ip_address", sa.String(45), nullable=True),
        sa.Column("location", sa.String(255), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("is_flagged", sa.Boolean(), nullable=False,
                  server_default=sa.text("false")),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["receiver_account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sender_account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_index("ix_transactions_transaction_id", "transactions", ["transaction_id"], unique=True)
    op.create_index("ix_transactions_sender_account_id", "transactions", ["sender_account_id"], unique=False)
    op.create_index("ix_transactions_receiver_account_id", "transactions", ["receiver_account_id"], unique=False)
    op.create_index("ix_transactions_timestamp", "transactions", ["timestamp"], unique=False)
    op.create_index("ix_transactions_sender_timestamp", "transactions", ["sender_account_id", "timestamp"], unique=False)
    op.create_index("ix_transactions_receiver_timestamp", "transactions", ["receiver_account_id", "timestamp"], unique=False)
    op.create_index("ix_transactions_status_timestamp", "transactions", ["status", "timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_status_timestamp", table_name="transactions")
    op.drop_index("ix_transactions_receiver_timestamp", table_name="transactions")
    op.drop_index("ix_transactions_sender_timestamp", table_name="transactions")
    op.drop_index("ix_transactions_timestamp", table_name="transactions")
    op.drop_index("ix_transactions_receiver_account_id", table_name="transactions")
    op.drop_index("ix_transactions_sender_account_id", table_name="transactions")
    op.drop_index("ix_transactions_transaction_id", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_accounts_user_id", table_name="accounts")
    op.drop_index("ix_accounts_account_number", table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###