"""Add full_name, password_hash, role to users table.

Revision ID: 2024_add_auth_fields_to_users
Revises: 2024_create_users_table
Create Date: 2024-01-15 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2024_add_auth_fields_to_users"
down_revision: Union[str, None] = "2024_create_users_table"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("full_name", sa.String(255), nullable=False, server_default=""),
    )
    op.add_column(
        "users",
        sa.Column("password_hash", sa.String(255), nullable=False, server_default=""),
    )
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.String(50),
            nullable=False,
            server_default="customer",
        ),
    )
    # Rename hashed_password to password_hash (handled by add + drop, data migration if needed)
    # Note: We'll drop the old column after ensuring password_hash is populated
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.String(), nullable=False, server_default=""),
    )
    op.drop_column("users", "role")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###